{{- range .Values.edgeApps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.global.cluster }}-{{ .name }}
  namespace: {{ $.Values.global.argocdConfig.hub_ns }}
spec:
  project: {{ $.Values.global.argocdConfig.edge_project }}
  {{- if ne $.Values.global.env "dev" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
  destination:
    server: {{ $.Values.clusterServer }}
    namespace: {{ .namespace }}
  source:
    repoURL: {{ .repoURL }}
    chart: {{ .chart }}
    targetRevision: {{ .targetRevision }}
{{- end }}
