global:
  machineRepo:
    url: https://github.com/Q29vbA/flavors-machine.git
    revision: feat/flavor-bootstrap
  definitionsRepo:
    url: https://github.com/Q29vbA/flavors-definition.git
    revision: feat/flavor-bootstrap
  env: dev
  argocdConfig:
    hub_ns: argocd
    hub_project: default
    edge_project: default
  baseDomain: hub.example.com

